In [2]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.datasets

## Assignment 1-1
동영상 데이터에 대한 Linear classifier를 구현해보세요

- Input data : 32 x 32 size, RGB channel, 100 frame
- the number of samples : 500

**Input data, weights, bias, score 가 출력될 수 있도록 구현해주세요**

In [5]:
# Assignment 1-1 구현은 여기서
vid_shape=[100,32,32,3] #이미지와 다르게 새로 추가된 차원인 프레임 값을 맨 앞에 넣음

num_class=10 #임의로 10개로 정함
num_sample=500 #주어진 값
data_shape=[100,32,32,3,num_sample] #비디오의 각 차원 + 샘플값까지 고려해 data_shape을 설정

vid_size=vid_shape[0]*vid_shape[1]*vid_shape[2]*vid_shape[3] #비디오의 각 차원을 곱해 사이즈 측정

x_data=np.random.randint(255,size=data_shape) #임의로 정한 비디오 데이터는 이런 형식을 띰
x=np.reshape(x_data, (-1,num_sample)) # input data를 size 307200 x 500으로 reshape해줌
W=np.random.normal(0,0.01,size=(num_class, vid_size)) #Weights (size 10 x 307200)
b=np.random.normal(0,1,size=(num_class, num_sample)) #bias (size 10 x 500)

s=np.dot(W,x)+b # score (size 10 x 500)

#데이터 사이즈에 맞게 W,x,b를 설정해 score값을 구하도록 하였음.
#x,W,b,s모두 직관적으로 보이지 않아서 배열 자체와 배열의 shape를 함께 출력하였음.
print(x,'<--x')
print('x shape is: ', x.shape, '\n')

print(W,'<--W')
print('W shape is: ', W.shape, '\n')

print(b, '<--b')
print('b shape is: ', b.shape, '\n')

print(s, '<--s')
print('s shape is: ', s.shape)

[[233 230 202 ... 152 224  68]
 [ 66 196 145 ...  96 204 241]
 [230   9  49 ...  18 103 106]
 ...
 [145  16 240 ... 104 216 199]
 [ 11  22  64 ... 230 131 251]
 [214 193 116 ... 152  93  55]] <--x
x shape is:  (307200, 500) 

[[-1.15755387e-02  3.20072332e-02 -6.78983688e-03 ...  4.00390480e-04
  -2.05691602e-03  2.35614265e-03]
 [ 6.42528581e-03  3.28768693e-04 -4.68737505e-03 ...  1.98721238e-02
   2.19012525e-03 -2.38510022e-02]
 [ 1.04923384e-02 -1.19159042e-02 -5.87290221e-04 ... -4.11282505e-05
  -1.08319419e-02 -3.63793866e-03]
 ...
 [ 3.95282305e-03  3.08597392e-03 -2.13694344e-02 ... -8.79922695e-04
  -6.91056679e-03  9.02700524e-03]
 [ 3.86654640e-03  1.44439544e-02  1.00666027e-02 ...  1.72935399e-02
  -1.46592120e-02  1.61388494e-03]
 [ 8.71701998e-04 -9.23996049e-03 -3.71513134e-03 ... -5.33041576e-03
  -5.18342506e-04 -4.21675474e-03]] <--W
W shape is:  (10, 307200) 

[[ 0.20762155  0.99028056 -0.44289771 ... -0.16252416 -0.56664207
  -0.9642863 ]
 [-0.60120532  0.3280399

##Assignment 1-2

1) L2 Regularization을 구현해보세요 (아래 Loss_reg 함수 참조)

- 코드만 구현하면 됩니다


2) 주어진 MNIST dataset을 이용하여 SVM loss와 Regularization loss를 구해보세요

- SVM loss와 L1, L2 Regularization loss를 모두 출력해 주세요

3) Total loss 구해보세요 (lambda = 0.1)

- lambda값을 0.1로 설정하여 total loss를 모두 출력해주세요

In [111]:
# SVM Loss 

def Loss_SVM(s, y):
    delta = 1.0
    [num_class, num_sample] = s.shape
    Li = 0
    for i in range(num_sample):
        ysample = y[:,i]
        ssample = s[:,i]
        ysample_index = np.where(ysample==1)[0][0]
        for j in range(num_class):
            if j == ysample_index:
                continue
            else:
                Li += max(0, ssample[j] - ssample[ysample_index] + delta)
    return Li/num_sample

In [112]:
# mnist data load

mnist = sklearn.datasets.fetch_openml('mnist_784', data_home="mnist_784")

num_sample = 5000
num_class = 10

x = mnist.data[:num_sample]
img_size = x[0].size
y_index = mnist.target[:num_sample]

y = np.zeros((num_class, num_sample))
for idx in range(num_sample):
    y[int(y_index[idx]), idx] = 1

In [113]:
# 1) Loss reg 구현은 여기서

def Loss_reg(W, dim=2):
    if dim == 1: # L1 regularization:
        reg = np.sum(abs(W))
    elif dim == 2:
        reg = np.sum(W**2) #L2는 W의 값들을 제곱해서 구현함.

    return reg

In [119]:
# 2) MNIST linear classifer 구현은 여기서
W=np.random.normal(0,0.002,size=(num_class, img_size))
#적절한 W를 찾을 수 있으면 좋겠지만 적당히 작은 수준에서 랜덤변수를 활용해 Weight값을 임의로 지정
b=np.random.normal(0,1,size=(num_class,num_sample)) #랜덤변수를 활용하고 Wx와 동일한 size를 가진 b형성

s=np.dot(W,x.T)+b
"""주어진 x데이터는 각 샘플이 가로축이고 그것이 5000개 쌓여있는 모양임. 이것은 우리가 기존에 구한
score나 y배열과는 다른 모양이므로 x.T로 dot product를 수행해서 배열의 모양을 맞춰줌."""

print('x shape is :', x.shape)
print('W shape is :', W.shape)
print('b shape is :', b.shape)
print('s shape is :', s.shape)

x shape is : (5000, 784)
W shape is : (10, 784)
b shape is : (10, 5000)
s shape is : (10, 5000)


In [120]:
# 3) Total Loss 구현은 여기서
loss=Loss_SVM(s,y) #SVM_Loss
reg_term_L1 = Loss_reg(W, dim=1) #L1
reg_term_L2 = Loss_reg(W, dim=2) #L2
print('total loss L1: ', loss+0.1*reg_term_L1) #L1 regularization을 사용
print('total loss L2: ', loss+0.1*reg_term_L2) #L2 regularization을 사용
#sainity check를 제대로 통과하는 것을 확인했다.
#주어진 값대로 하이퍼파라미터의 값을 0.1로 설정하였다.
print('svm loss: ', loss)

total loss L1:  34.716314590253
total loss L2:  33.45511176146328
svm loss:  33.45190696460981
